version: '3.8'

services:
  api-service:
      build: ./final-api/
      volumes:
          - ./final-api/:/usr/src/app/
      ports: 
          - 8001:8001
      environment: 
          PORT: 8001
          FLASK_DEBUG: 1

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: group
      POSTGRES_PASSWORD: project
      POSTGRES_DB: final_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    user: root
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgAdmin/servers.json:/pgadmin4/servers.json

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    environment:
      JUPYTER_TOKEN: myjupyterpassword
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data # Shared data volume
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.6.2
    container_name: airflow
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://group:project@postgres:5432/final_db
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./data:/opt/airflow/data  # Shared data volume
    depends_on:
      - postgres
    command: >
      bash -c "
        airflow db init &&
        airflow db upgrade &&
        airflow users list | grep -q 'admin' || airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow webserver & airflow scheduler
        airflow dags list | awk '{print $1}' | tail -n +2 | xargs -I {} airflow dags trigger {}
      "

volumes:
  pgdata:
  pgadmin-data:
  dags:
  logs:
  plugins:

# Local Host Access
# api: http://localhost:5000
# Airflow: http://localhost:8081
# PgAdmin: http://localhost:8080
# Jupyter: http://localhost:8888

# Database Credentials
# database="final_db",
# host="host.docker.internal",
# user="group",
# password="project",
# port="5432"
